name: Test package

on: [push]
jobs:

  test-code:
    # This code depends on the result of check-code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-08-16


    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
          key: cache_v1
          restore-keys: |
            cache_v1

      - name: Install package
        run: python3 -m pip install -e .[test]

      - name: Run tests
        run: python3 -m pytest

      - name: Coverage report
        if: github.ref == 'refs/heads/main'
        run: |
          python3 -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
          python3 -m coverage json
          export TOTAL=$(python3 -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV

      - name: Upload HTML report.
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: htmlcov
